title: Polymer-cdn
description: A mirror of Polymer's components so that they can be used directly from CDN
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
